# Generated by Django 4.2.1 on 2023-05-15 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('animal_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], default='Dog', max_length=20)),
                ('breed_type', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('city', models.CharField(default='Unknown', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='')),
                ('foster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interested', models.ManyToManyField(related_name='interested_pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
