# Generated by Django 4.2.1 on 2023-05-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
