# Generated by Django 4.2.1 on 2023-05-19 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.userprofile')),
            ],
        ),
    ]
